select * from tbl_persona;
select * from tbl_clientes;
select * from tbl_empleados;
select * from tbl_proveedores;
select * from tbl_productos;

SELECT PER.PERS_ID id FROM TBL_PERSONA PER WHERE PER.PERS_CEDULA='0106495856';

SELECT 	CLI.CLI_CODIGO, PER.PERS_CEDULA, PER.PERS_NOMBRES, PER.PERS_APELLIDOS, PER.PERS_TELEFONO1, PER.PERS_TELEFONO2, PER.PERS_DIRECCION, PER.PERS_CORREO_ELECTRONICO FROM TBL_PERSONA PER, TBL_CLIENTES CLI WHERE PER.PERS_ID=CLI.PERS_ID ORDER BY PER.PERS_CEDULA;
SELECT 	PER.PERS_ID, EMP.EMPLE_CODIGO, PER.PERS_CEDULA, PER.PERS_NOMBRES, PER.PERS_APELLIDOS, PER.PERS_TELEFONO1, PER.PERS_TELEFONO2, PER.PERS_DIRECCION, PER.PERS_CORREO_ELECTRONICO, EMP.EMPLE_CARGO FROM TBL_PERSONA PER, TBL_EMPLEADOS EMP WHERE PER.PERS_ID=EMP.PERS_ID ORDER BY PER.PERS_CEDULA;

INSERT INTO TBL_PERSONA VALUES (0, '1708844772', 'Wilson Fernando', 'Zambrano Vintimilla', '0987143941', '072810963', 'Calle del Batán y Guayas', 'wilsonzambranoht@hotmail.com');
INSERT INTO TBL_EMPLEADOS VALUES (0,'WFZV0003',1);
INSERT INTO TBL_CLIENTES VALUES (0,'WFZV0003',1);
INSERT INTO TBL_PRODUCTOS VALUES (0,'NOMBRE','ALGO', 10.30, 100, 1);

UPDATE TBL_PERSONA SET PERS_NOMBRES = 'Mercedes Ines' WHERE PERS_ID = 9;
UPDATE TBL_EMPLEADOS SET EMPLE_CARGO = 'SECRCETARIA' WHERE PERS_ID = 16;

SELECT 
	PER.PERS_CEDULA, PER.PERS_NOMBRES, PER.PERS_APELLIDOS, PER.PERS_TELEFONO1, PER.PERS_TELEFONO2, PER.PERS_DIRECCION, PER.PERS_CORREO_ELECTRONICO 
FROM 
	TBL_PERSONA PER 
WHERE 
    PER.PERS_CEDULA LIKE '%5%' OR PER.PERS_NOMBRES LIKE '%6%' OR PER.PERS_APELLIDOS LIKE '%6%';
    
    
    
DELETE FROM TBL_CLIENTES WHERE PERS_ID = 5;    
DELETE FROM TBL_PERSONA WHERE PERS_ID = 5;


SELECT 
	PERS.PERS_ID, EMP.EMPLE_CODIGO, PERS.PERS_CEDULA, PERS.PERS_NOMBRES, PERS.PERS_APELLIDOS, PERS.PERS_TELEFONO1, PERS.PERS_TELEFONO2, PERS.PERS_DIRECCION, PERS.PERS_CORREO_ELECTRONICO, EMP.EMPLE_CARGO
FROM
	TBL_PERSONA PERS, TBL_EMPLEADOS EMP
WHERE
	PERS.PERS_ID=EMP.PERS_ID AND PERS.PERS_CEDULA LIKE '%5%'